// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:xfiat_fluttify/src/ios/ios.export.g.dart';
import 'package:xfiat_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

class com_iflytek_cloud_util_ResourceUtil extends java_lang_Object  {
  //region constants
  static final String ENGINE_START = "engine_start";
  static final String ENGINE_DESTROY = "engine_destroy";
  static final String ASR_RES_PATH = "asr_res_path";
  static final String GRM_BUILD_PATH = "grm_build_path";
  static final String TTS_RES_PATH = "tts_res_path";
  static final String IVW_RES_PATH = "ivw_res_path";
  //endregion

  //region creators
  static Future<com_iflytek_cloud_util_ResourceUtil> create__() async {
    final int refId = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('ObjectFactory::createcom_iflytek_cloud_util_ResourceUtil__');
    final object = com_iflytek_cloud_util_ResourceUtil()..refId = refId..tag = 'xfiat_fluttify';
  
    kNativeObjectPool.add(object);
    return object;
  }
  
  //endregion

  //region getters
  
  //endregion

  //region setters
  
  //endregion

  //region methods
  static Future<String> generateResourcePath(android_content_Context var0, com_iflytek_cloud_util_ResourceUtil_RESOURCE_TYPE var1, String var2) async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.iflytek.cloud.util.ResourceUtil::generateResourcePath([\'var2\':$var2])');
    }
  
    // invoke native method
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('com.iflytek.cloud.util.ResourceUtil::generateResourcePath', {"var0": var0.refId, "var1": var1.index, "var2": var2});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
    
      return result;
    }
  }
  
  //endregion
}