// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:xfiat_fluttify/src/ios/ios.export.g.dart';
import 'package:xfiat_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

class com_iflytek_cloud_speech_impl_SpeechSynthesizerImpl extends java_lang_Object  {
  //region constants
  
  //endregion

  //region creators
  static Future<com_iflytek_cloud_speech_impl_SpeechSynthesizerImpl> create__android_content_Context(android_content_Context var1) async {
    final int refId = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('ObjectFactory::createcom_iflytek_cloud_speech_impl_SpeechSynthesizerImpl__android_content_Context', {"var1": var1.refId});
    final object = com_iflytek_cloud_speech_impl_SpeechSynthesizerImpl()..refId = refId..tag = 'xfiat_fluttify';
  
    kNativeObjectPool.add(object);
    return object;
  }
  
  //endregion

  //region getters
  
  //endregion

  //region setters
  
  //endregion

  //region methods
  Future<int> startSpeaking(String var1, com_iflytek_cloud_SynthesizerListener var2) async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.iflytek.cloud.speech.impl.SpeechSynthesizerImpl@$refId::startSpeaking([\'var1\':$var1])');
    }
  
    // invoke native method
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('com.iflytek.cloud.speech.impl.SpeechSynthesizerImpl::startSpeaking', {"var1": var1, "refId": refId});
  
  
    // handle native call
    MethodChannel('com.iflytek.cloud.speech.impl.SpeechSynthesizerImpl::startSpeaking::Callback')
        .setMethodCallHandler((methodCall) async {
          final args = methodCall.arguments as Map;
          // final refId = args['callerRefId'] as int;
          // if (refId != this.refId) return;
  
          switch (methodCall.method) {
            case 'Callback::com.iflytek.cloud.SynthesizerListener::onSpeakBegin':
              // print log
              if (fluttifyLogEnabled) {
                print('fluttify-dart-callback: onSpeakBegin([])');
              }
        
              // handle the native call
              var2?.onSpeakBegin();
              break;
            case 'Callback::com.iflytek.cloud.SynthesizerListener::onBufferProgress':
              // print log
              if (fluttifyLogEnabled) {
                print('fluttify-dart-callback: onBufferProgress([\'var1\':$args[var1], \'var2\':$args[var2], \'var3\':$args[var3], \'var4\':$args[var4]])');
              }
        
              // handle the native call
              var2?.onBufferProgress(args['var1'], args['var2'], args['var3'], args['var4']);
              break;
            case 'Callback::com.iflytek.cloud.SynthesizerListener::onSpeakPaused':
              // print log
              if (fluttifyLogEnabled) {
                print('fluttify-dart-callback: onSpeakPaused([])');
              }
        
              // handle the native call
              var2?.onSpeakPaused();
              break;
            case 'Callback::com.iflytek.cloud.SynthesizerListener::onSpeakResumed':
              // print log
              if (fluttifyLogEnabled) {
                print('fluttify-dart-callback: onSpeakResumed([])');
              }
        
              // handle the native call
              var2?.onSpeakResumed();
              break;
            case 'Callback::com.iflytek.cloud.SynthesizerListener::onSpeakProgress':
              // print log
              if (fluttifyLogEnabled) {
                print('fluttify-dart-callback: onSpeakProgress([\'var1\':$args[var1], \'var2\':$args[var2], \'var3\':$args[var3]])');
              }
        
              // handle the native call
              var2?.onSpeakProgress(args['var1'], args['var2'], args['var3']);
              break;
            case 'Callback::com.iflytek.cloud.SynthesizerListener::onCompleted':
              // print log
              if (fluttifyLogEnabled) {
                print('fluttify-dart-callback: onCompleted([])');
              }
        
              // handle the native call
              var2?.onCompleted(com_iflytek_cloud_SpeechError()..refId = (args['var1'])..tag = 'xfiat_fluttify');
              break;
            case 'Callback::com.iflytek.cloud.SynthesizerListener::onEvent':
              // print log
              if (fluttifyLogEnabled) {
                print('fluttify-dart-callback: onEvent([\'var1\':$args[var1], \'var2\':$args[var2], \'var3\':$args[var3]])');
              }
        
              // handle the native call
              var2?.onEvent(args['var1'], args['var2'], args['var3'], android_os_Bundle()..refId = (args['var4'])..tag = 'xfiat_fluttify');
              break;
            default:
              break;
          }
        });
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
    
      return result;
    }
  }
  
  Future<int> synthesizeToUri(String var1, String var2, com_iflytek_cloud_SynthesizerListener var3) async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.iflytek.cloud.speech.impl.SpeechSynthesizerImpl@$refId::synthesizeToUri([\'var1\':$var1, \'var2\':$var2])');
    }
  
    // invoke native method
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('com.iflytek.cloud.speech.impl.SpeechSynthesizerImpl::synthesizeToUri', {"var1": var1, "var2": var2, "refId": refId});
  
  
    // handle native call
    MethodChannel('com.iflytek.cloud.speech.impl.SpeechSynthesizerImpl::synthesizeToUri::Callback')
        .setMethodCallHandler((methodCall) async {
          final args = methodCall.arguments as Map;
          // final refId = args['callerRefId'] as int;
          // if (refId != this.refId) return;
  
          switch (methodCall.method) {
            case 'Callback::com.iflytek.cloud.SynthesizerListener::onSpeakBegin':
              // print log
              if (fluttifyLogEnabled) {
                print('fluttify-dart-callback: onSpeakBegin([])');
              }
        
              // handle the native call
              var3?.onSpeakBegin();
              break;
            case 'Callback::com.iflytek.cloud.SynthesizerListener::onBufferProgress':
              // print log
              if (fluttifyLogEnabled) {
                print('fluttify-dart-callback: onBufferProgress([\'var1\':$args[var1], \'var2\':$args[var2], \'var3\':$args[var3], \'var4\':$args[var4]])');
              }
        
              // handle the native call
              var3?.onBufferProgress(args['var1'], args['var2'], args['var3'], args['var4']);
              break;
            case 'Callback::com.iflytek.cloud.SynthesizerListener::onSpeakPaused':
              // print log
              if (fluttifyLogEnabled) {
                print('fluttify-dart-callback: onSpeakPaused([])');
              }
        
              // handle the native call
              var3?.onSpeakPaused();
              break;
            case 'Callback::com.iflytek.cloud.SynthesizerListener::onSpeakResumed':
              // print log
              if (fluttifyLogEnabled) {
                print('fluttify-dart-callback: onSpeakResumed([])');
              }
        
              // handle the native call
              var3?.onSpeakResumed();
              break;
            case 'Callback::com.iflytek.cloud.SynthesizerListener::onSpeakProgress':
              // print log
              if (fluttifyLogEnabled) {
                print('fluttify-dart-callback: onSpeakProgress([\'var1\':$args[var1], \'var2\':$args[var2], \'var3\':$args[var3]])');
              }
        
              // handle the native call
              var3?.onSpeakProgress(args['var1'], args['var2'], args['var3']);
              break;
            case 'Callback::com.iflytek.cloud.SynthesizerListener::onCompleted':
              // print log
              if (fluttifyLogEnabled) {
                print('fluttify-dart-callback: onCompleted([])');
              }
        
              // handle the native call
              var3?.onCompleted(com_iflytek_cloud_SpeechError()..refId = (args['var1'])..tag = 'xfiat_fluttify');
              break;
            case 'Callback::com.iflytek.cloud.SynthesizerListener::onEvent':
              // print log
              if (fluttifyLogEnabled) {
                print('fluttify-dart-callback: onEvent([\'var1\':$args[var1], \'var2\':$args[var2], \'var3\':$args[var3]])');
              }
        
              // handle the native call
              var3?.onEvent(args['var1'], args['var2'], args['var3'], android_os_Bundle()..refId = (args['var4'])..tag = 'xfiat_fluttify');
              break;
            default:
              break;
          }
        });
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
    
      return result;
    }
  }
  
  Future<void> pauseSpeaking() async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.iflytek.cloud.speech.impl.SpeechSynthesizerImpl@$refId::pauseSpeaking([])');
    }
  
    // invoke native method
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('com.iflytek.cloud.speech.impl.SpeechSynthesizerImpl::pauseSpeaking', {"refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
    
      return result;
    }
  }
  
  Future<void> replaySpeaking() async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.iflytek.cloud.speech.impl.SpeechSynthesizerImpl@$refId::replaySpeaking([])');
    }
  
    // invoke native method
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('com.iflytek.cloud.speech.impl.SpeechSynthesizerImpl::replaySpeaking', {"refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
    
      return result;
    }
  }
  
  Future<void> resumeSpeaking() async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.iflytek.cloud.speech.impl.SpeechSynthesizerImpl@$refId::resumeSpeaking([])');
    }
  
    // invoke native method
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('com.iflytek.cloud.speech.impl.SpeechSynthesizerImpl::resumeSpeaking', {"refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
    
      return result;
    }
  }
  
  Future<bool> isSpeaking() async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.iflytek.cloud.speech.impl.SpeechSynthesizerImpl@$refId::isSpeaking([])');
    }
  
    // invoke native method
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('com.iflytek.cloud.speech.impl.SpeechSynthesizerImpl::isSpeaking', {"refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
    
      return result;
    }
  }
  
  Future<int> getState() async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.iflytek.cloud.speech.impl.SpeechSynthesizerImpl@$refId::getState([])');
    }
  
    // invoke native method
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('com.iflytek.cloud.speech.impl.SpeechSynthesizerImpl::getState', {"refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
    
      return result;
    }
  }
  
  Future<void> stopSpeaking(bool var1) async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.iflytek.cloud.speech.impl.SpeechSynthesizerImpl@$refId::stopSpeaking([\'var1\':$var1])');
    }
  
    // invoke native method
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('com.iflytek.cloud.speech.impl.SpeechSynthesizerImpl::stopSpeaking', {"var1": var1, "refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
    
      return result;
    }
  }
  
  Future<int> getDownflowBytes(bool var1) async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.iflytek.cloud.speech.impl.SpeechSynthesizerImpl@$refId::getDownflowBytes([\'var1\':$var1])');
    }
  
    // invoke native method
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('com.iflytek.cloud.speech.impl.SpeechSynthesizerImpl::getDownflowBytes', {"var1": var1, "refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
    
      return result;
    }
  }
  
  Future<int> getUpflowBytes(bool var1) async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.iflytek.cloud.speech.impl.SpeechSynthesizerImpl@$refId::getUpflowBytes([\'var1\':$var1])');
    }
  
    // invoke native method
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('com.iflytek.cloud.speech.impl.SpeechSynthesizerImpl::getUpflowBytes', {"var1": var1, "refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
    
      return result;
    }
  }
  
  //endregion
}