// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:xfiat_fluttify/src/android/android.export.g.dart';
import 'package:xfiat_fluttify/src/ios/ios.export.g.dart';

// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import
extension TypeOpXfiatFluttifyAndroid on Ref {
  Future<bool> iscom_iflytek_speech_SpeechComponent() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_speech_SpeechComponent', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_speech_SpeakerVerifierAidl() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_speech_SpeakerVerifierAidl', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_speech_SpeechUnderstanderAidl() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_speech_SpeechUnderstanderAidl', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_speech_SpeechRecognizerAidl() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_speech_SpeechRecognizerAidl', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_speech_SpeechSynthesizerAidl() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_speech_SpeechSynthesizerAidl', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_speech_UtilityConfig() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_speech_UtilityConfig', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_speech_SpeakerVerifierAidl_PassWord() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_speech_SpeakerVerifierAidl_PassWord', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_speech_WakeuperResult() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_speech_WakeuperResult', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_speech_VerifierResult() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_speech_VerifierResult', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_speech_RecognizerResult() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_speech_RecognizerResult', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_speech_Version() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_speech_Version', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_speech_TextUnderstanderAidl() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_speech_TextUnderstanderAidl', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_speech_UnderstanderResult() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_speech_UnderstanderResult', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_speech_VoiceWakeuperAidl() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_speech_VoiceWakeuperAidl', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_idata_extension_IFlyCollectorExt() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_idata_extension_IFlyCollectorExt', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_cloud_ErrorCode() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_cloud_ErrorCode', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_cloud_record_PcmRecorder() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_cloud_record_PcmRecorder', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_cloud_util_AudioDetector() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_cloud_util_AudioDetector', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_cloud_util_UserWords() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_cloud_util_UserWords', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_cloud_util_VerifierUtil() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_cloud_util_VerifierUtil', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_cloud_util_ResourceUtil() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_cloud_util_ResourceUtil', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_cloud_util_AudioDetector_DetectorResult() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_cloud_util_AudioDetector_DetectorResult', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_cloud_util_Accelerometer() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_cloud_util_Accelerometer', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_cloud_util_ContactManager() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_cloud_util_ContactManager', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_cloud_util_VolumeUtil() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_cloud_util_VolumeUtil', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_cloud_IdentityResult() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_cloud_IdentityResult', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_cloud_speech_impl_FaceDetectorImpl() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_cloud_speech_impl_FaceDetectorImpl', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_cloud_speech_impl_SpeechUnderstanderImpl() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_cloud_speech_impl_SpeechUnderstanderImpl', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_cloud_msc_util_FuncAdapterSdk10() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_cloud_msc_util_FuncAdapterSdk10', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_cloud_msc_util_NetworkUtil() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_cloud_msc_util_NetworkUtil', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_cloud_msc_util_Base64() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_cloud_msc_util_Base64', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_cloud_msc_util_DataUtil() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_cloud_msc_util_DataUtil', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_cloud_msc_util_RSAUtil() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_cloud_msc_util_RSAUtil', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_cloud_msc_util_Encrypter() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_cloud_msc_util_Encrypter', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_cloud_msc_util_AppInfoUtil() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_cloud_msc_util_AppInfoUtil', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_cloud_msc_util_FileUtil() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_cloud_msc_util_FileUtil', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_cloud_msc_util_DataLogger() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_cloud_msc_util_DataLogger', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_cloud_msc_util_SDCardHelper() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_cloud_msc_util_SDCardHelper', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_cloud_msc_util_http_HttpDownloadImpl() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_cloud_msc_util_http_HttpDownloadImpl', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_cloud_msc_util_FuncAdapter() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_cloud_msc_util_FuncAdapter', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_cloud_msc_util_Config() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_cloud_msc_util_Config', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_cloud_msc_util_log_PerfLogger() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_cloud_msc_util_log_PerfLogger', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_cloud_msc_util_log_DebugLog() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_cloud_msc_util_log_DebugLog', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_cloud_msc_util_UniqueIDUtil() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_cloud_msc_util_UniqueIDUtil', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_cloud_msc_util_FileDownloader() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_cloud_msc_util_FileDownloader', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_cloud_msc_util_AESUtil() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_cloud_msc_util_AESUtil', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_cloud_msc_util_HttpRequest() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_cloud_msc_util_HttpRequest', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_cloud_msc_ist_AudioAccessor() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_cloud_msc_ist_AudioAccessor', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_cloud_SpeechError() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_cloud_SpeechError', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_cloud_Setting() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_cloud_Setting', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_cloud_EvaluatorResult() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_cloud_EvaluatorResult', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_cloud_SpeechEvent() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_cloud_SpeechEvent', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_cloud_resource_Resource() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_cloud_resource_Resource', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_cloud_WakeuperResult() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_cloud_WakeuperResult', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_cloud_VerifierResult() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_cloud_VerifierResult', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_cloud_SpeechConstant() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_cloud_SpeechConstant', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_cloud_RecognizerResult() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_cloud_RecognizerResult', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_cloud_TranscripterResult() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_cloud_TranscripterResult', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_cloud_Version() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_cloud_Version', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_cloud_UnderstanderResult() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_cloud_UnderstanderResult', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_msc_VAD_VadData() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_msc_VAD_VadData', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_msc_MSCSessionInfo() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_msc_MSCSessionInfo', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_msc_MetaVAD() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_msc_MetaVAD', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_msc_VAD() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_msc_VAD', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_msc_AIMIC() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_msc_AIMIC', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_msc_MSC() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_msc_MSC', {'refId': refId});
    return result;
  }
  
  Future<bool> iscom_iflytek_msc_MetaVAD_Instance() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::isKindOfcom_iflytek_msc_MetaVAD_Instance', {'refId': refId});
    return result;
  }
  

  Future<com_iflytek_speech_SpeechComponent> ascom_iflytek_speech_SpeechComponent() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_speech_SpeechComponent', {'refId': refId});
    return com_iflytek_speech_SpeechComponent()..refId = result;
  }
  
  Future<com_iflytek_speech_SpeakerVerifierAidl> ascom_iflytek_speech_SpeakerVerifierAidl() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_speech_SpeakerVerifierAidl', {'refId': refId});
    return com_iflytek_speech_SpeakerVerifierAidl()..refId = result;
  }
  
  Future<com_iflytek_speech_SpeechUnderstanderAidl> ascom_iflytek_speech_SpeechUnderstanderAidl() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_speech_SpeechUnderstanderAidl', {'refId': refId});
    return com_iflytek_speech_SpeechUnderstanderAidl()..refId = result;
  }
  
  Future<com_iflytek_speech_SpeechRecognizerAidl> ascom_iflytek_speech_SpeechRecognizerAidl() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_speech_SpeechRecognizerAidl', {'refId': refId});
    return com_iflytek_speech_SpeechRecognizerAidl()..refId = result;
  }
  
  Future<com_iflytek_speech_SpeechSynthesizerAidl> ascom_iflytek_speech_SpeechSynthesizerAidl() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_speech_SpeechSynthesizerAidl', {'refId': refId});
    return com_iflytek_speech_SpeechSynthesizerAidl()..refId = result;
  }
  
  Future<com_iflytek_speech_UtilityConfig> ascom_iflytek_speech_UtilityConfig() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_speech_UtilityConfig', {'refId': refId});
    return com_iflytek_speech_UtilityConfig()..refId = result;
  }
  
  Future<com_iflytek_speech_SpeakerVerifierAidl_PassWord> ascom_iflytek_speech_SpeakerVerifierAidl_PassWord() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_speech_SpeakerVerifierAidl_PassWord', {'refId': refId});
    return com_iflytek_speech_SpeakerVerifierAidl_PassWord()..refId = result;
  }
  
  Future<com_iflytek_speech_WakeuperResult> ascom_iflytek_speech_WakeuperResult() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_speech_WakeuperResult', {'refId': refId});
    return com_iflytek_speech_WakeuperResult()..refId = result;
  }
  
  Future<com_iflytek_speech_VerifierResult> ascom_iflytek_speech_VerifierResult() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_speech_VerifierResult', {'refId': refId});
    return com_iflytek_speech_VerifierResult()..refId = result;
  }
  
  Future<com_iflytek_speech_RecognizerResult> ascom_iflytek_speech_RecognizerResult() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_speech_RecognizerResult', {'refId': refId});
    return com_iflytek_speech_RecognizerResult()..refId = result;
  }
  
  Future<com_iflytek_speech_Version> ascom_iflytek_speech_Version() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_speech_Version', {'refId': refId});
    return com_iflytek_speech_Version()..refId = result;
  }
  
  Future<com_iflytek_speech_TextUnderstanderAidl> ascom_iflytek_speech_TextUnderstanderAidl() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_speech_TextUnderstanderAidl', {'refId': refId});
    return com_iflytek_speech_TextUnderstanderAidl()..refId = result;
  }
  
  Future<com_iflytek_speech_UnderstanderResult> ascom_iflytek_speech_UnderstanderResult() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_speech_UnderstanderResult', {'refId': refId});
    return com_iflytek_speech_UnderstanderResult()..refId = result;
  }
  
  Future<com_iflytek_speech_VoiceWakeuperAidl> ascom_iflytek_speech_VoiceWakeuperAidl() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_speech_VoiceWakeuperAidl', {'refId': refId});
    return com_iflytek_speech_VoiceWakeuperAidl()..refId = result;
  }
  
  Future<com_iflytek_idata_extension_IFlyCollectorExt> ascom_iflytek_idata_extension_IFlyCollectorExt() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_idata_extension_IFlyCollectorExt', {'refId': refId});
    return com_iflytek_idata_extension_IFlyCollectorExt()..refId = result;
  }
  
  Future<com_iflytek_cloud_ErrorCode> ascom_iflytek_cloud_ErrorCode() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_cloud_ErrorCode', {'refId': refId});
    return com_iflytek_cloud_ErrorCode()..refId = result;
  }
  
  Future<com_iflytek_cloud_record_PcmRecorder> ascom_iflytek_cloud_record_PcmRecorder() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_cloud_record_PcmRecorder', {'refId': refId});
    return com_iflytek_cloud_record_PcmRecorder()..refId = result;
  }
  
  Future<com_iflytek_cloud_util_AudioDetector> ascom_iflytek_cloud_util_AudioDetector() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_cloud_util_AudioDetector', {'refId': refId});
    return com_iflytek_cloud_util_AudioDetector()..refId = result;
  }
  
  Future<com_iflytek_cloud_util_UserWords> ascom_iflytek_cloud_util_UserWords() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_cloud_util_UserWords', {'refId': refId});
    return com_iflytek_cloud_util_UserWords()..refId = result;
  }
  
  Future<com_iflytek_cloud_util_VerifierUtil> ascom_iflytek_cloud_util_VerifierUtil() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_cloud_util_VerifierUtil', {'refId': refId});
    return com_iflytek_cloud_util_VerifierUtil()..refId = result;
  }
  
  Future<com_iflytek_cloud_util_ResourceUtil> ascom_iflytek_cloud_util_ResourceUtil() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_cloud_util_ResourceUtil', {'refId': refId});
    return com_iflytek_cloud_util_ResourceUtil()..refId = result;
  }
  
  Future<com_iflytek_cloud_util_AudioDetector_DetectorResult> ascom_iflytek_cloud_util_AudioDetector_DetectorResult() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_cloud_util_AudioDetector_DetectorResult', {'refId': refId});
    return com_iflytek_cloud_util_AudioDetector_DetectorResult()..refId = result;
  }
  
  Future<com_iflytek_cloud_util_Accelerometer> ascom_iflytek_cloud_util_Accelerometer() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_cloud_util_Accelerometer', {'refId': refId});
    return com_iflytek_cloud_util_Accelerometer()..refId = result;
  }
  
  Future<com_iflytek_cloud_util_ContactManager> ascom_iflytek_cloud_util_ContactManager() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_cloud_util_ContactManager', {'refId': refId});
    return com_iflytek_cloud_util_ContactManager()..refId = result;
  }
  
  Future<com_iflytek_cloud_util_VolumeUtil> ascom_iflytek_cloud_util_VolumeUtil() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_cloud_util_VolumeUtil', {'refId': refId});
    return com_iflytek_cloud_util_VolumeUtil()..refId = result;
  }
  
  Future<com_iflytek_cloud_IdentityResult> ascom_iflytek_cloud_IdentityResult() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_cloud_IdentityResult', {'refId': refId});
    return com_iflytek_cloud_IdentityResult()..refId = result;
  }
  
  Future<com_iflytek_cloud_speech_impl_FaceDetectorImpl> ascom_iflytek_cloud_speech_impl_FaceDetectorImpl() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_cloud_speech_impl_FaceDetectorImpl', {'refId': refId});
    return com_iflytek_cloud_speech_impl_FaceDetectorImpl()..refId = result;
  }
  
  Future<com_iflytek_cloud_speech_impl_SpeechUnderstanderImpl> ascom_iflytek_cloud_speech_impl_SpeechUnderstanderImpl() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_cloud_speech_impl_SpeechUnderstanderImpl', {'refId': refId});
    return com_iflytek_cloud_speech_impl_SpeechUnderstanderImpl()..refId = result;
  }
  
  Future<com_iflytek_cloud_msc_util_FuncAdapterSdk10> ascom_iflytek_cloud_msc_util_FuncAdapterSdk10() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_cloud_msc_util_FuncAdapterSdk10', {'refId': refId});
    return com_iflytek_cloud_msc_util_FuncAdapterSdk10()..refId = result;
  }
  
  Future<com_iflytek_cloud_msc_util_NetworkUtil> ascom_iflytek_cloud_msc_util_NetworkUtil() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_cloud_msc_util_NetworkUtil', {'refId': refId});
    return com_iflytek_cloud_msc_util_NetworkUtil()..refId = result;
  }
  
  Future<com_iflytek_cloud_msc_util_Base64> ascom_iflytek_cloud_msc_util_Base64() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_cloud_msc_util_Base64', {'refId': refId});
    return com_iflytek_cloud_msc_util_Base64()..refId = result;
  }
  
  Future<com_iflytek_cloud_msc_util_DataUtil> ascom_iflytek_cloud_msc_util_DataUtil() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_cloud_msc_util_DataUtil', {'refId': refId});
    return com_iflytek_cloud_msc_util_DataUtil()..refId = result;
  }
  
  Future<com_iflytek_cloud_msc_util_RSAUtil> ascom_iflytek_cloud_msc_util_RSAUtil() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_cloud_msc_util_RSAUtil', {'refId': refId});
    return com_iflytek_cloud_msc_util_RSAUtil()..refId = result;
  }
  
  Future<com_iflytek_cloud_msc_util_Encrypter> ascom_iflytek_cloud_msc_util_Encrypter() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_cloud_msc_util_Encrypter', {'refId': refId});
    return com_iflytek_cloud_msc_util_Encrypter()..refId = result;
  }
  
  Future<com_iflytek_cloud_msc_util_AppInfoUtil> ascom_iflytek_cloud_msc_util_AppInfoUtil() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_cloud_msc_util_AppInfoUtil', {'refId': refId});
    return com_iflytek_cloud_msc_util_AppInfoUtil()..refId = result;
  }
  
  Future<com_iflytek_cloud_msc_util_FileUtil> ascom_iflytek_cloud_msc_util_FileUtil() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_cloud_msc_util_FileUtil', {'refId': refId});
    return com_iflytek_cloud_msc_util_FileUtil()..refId = result;
  }
  
  Future<com_iflytek_cloud_msc_util_DataLogger> ascom_iflytek_cloud_msc_util_DataLogger() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_cloud_msc_util_DataLogger', {'refId': refId});
    return com_iflytek_cloud_msc_util_DataLogger()..refId = result;
  }
  
  Future<com_iflytek_cloud_msc_util_SDCardHelper> ascom_iflytek_cloud_msc_util_SDCardHelper() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_cloud_msc_util_SDCardHelper', {'refId': refId});
    return com_iflytek_cloud_msc_util_SDCardHelper()..refId = result;
  }
  
  Future<com_iflytek_cloud_msc_util_http_HttpDownloadImpl> ascom_iflytek_cloud_msc_util_http_HttpDownloadImpl() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_cloud_msc_util_http_HttpDownloadImpl', {'refId': refId});
    return com_iflytek_cloud_msc_util_http_HttpDownloadImpl()..refId = result;
  }
  
  Future<com_iflytek_cloud_msc_util_FuncAdapter> ascom_iflytek_cloud_msc_util_FuncAdapter() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_cloud_msc_util_FuncAdapter', {'refId': refId});
    return com_iflytek_cloud_msc_util_FuncAdapter()..refId = result;
  }
  
  Future<com_iflytek_cloud_msc_util_Config> ascom_iflytek_cloud_msc_util_Config() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_cloud_msc_util_Config', {'refId': refId});
    return com_iflytek_cloud_msc_util_Config()..refId = result;
  }
  
  Future<com_iflytek_cloud_msc_util_log_PerfLogger> ascom_iflytek_cloud_msc_util_log_PerfLogger() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_cloud_msc_util_log_PerfLogger', {'refId': refId});
    return com_iflytek_cloud_msc_util_log_PerfLogger()..refId = result;
  }
  
  Future<com_iflytek_cloud_msc_util_log_DebugLog> ascom_iflytek_cloud_msc_util_log_DebugLog() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_cloud_msc_util_log_DebugLog', {'refId': refId});
    return com_iflytek_cloud_msc_util_log_DebugLog()..refId = result;
  }
  
  Future<com_iflytek_cloud_msc_util_UniqueIDUtil> ascom_iflytek_cloud_msc_util_UniqueIDUtil() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_cloud_msc_util_UniqueIDUtil', {'refId': refId});
    return com_iflytek_cloud_msc_util_UniqueIDUtil()..refId = result;
  }
  
  Future<com_iflytek_cloud_msc_util_FileDownloader> ascom_iflytek_cloud_msc_util_FileDownloader() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_cloud_msc_util_FileDownloader', {'refId': refId});
    return com_iflytek_cloud_msc_util_FileDownloader()..refId = result;
  }
  
  Future<com_iflytek_cloud_msc_util_AESUtil> ascom_iflytek_cloud_msc_util_AESUtil() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_cloud_msc_util_AESUtil', {'refId': refId});
    return com_iflytek_cloud_msc_util_AESUtil()..refId = result;
  }
  
  Future<com_iflytek_cloud_msc_util_HttpRequest> ascom_iflytek_cloud_msc_util_HttpRequest() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_cloud_msc_util_HttpRequest', {'refId': refId});
    return com_iflytek_cloud_msc_util_HttpRequest()..refId = result;
  }
  
  Future<com_iflytek_cloud_msc_ist_AudioAccessor> ascom_iflytek_cloud_msc_ist_AudioAccessor() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_cloud_msc_ist_AudioAccessor', {'refId': refId});
    return com_iflytek_cloud_msc_ist_AudioAccessor()..refId = result;
  }
  
  Future<com_iflytek_cloud_SpeechError> ascom_iflytek_cloud_SpeechError() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_cloud_SpeechError', {'refId': refId});
    return com_iflytek_cloud_SpeechError()..refId = result;
  }
  
  Future<com_iflytek_cloud_Setting> ascom_iflytek_cloud_Setting() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_cloud_Setting', {'refId': refId});
    return com_iflytek_cloud_Setting()..refId = result;
  }
  
  Future<com_iflytek_cloud_EvaluatorResult> ascom_iflytek_cloud_EvaluatorResult() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_cloud_EvaluatorResult', {'refId': refId});
    return com_iflytek_cloud_EvaluatorResult()..refId = result;
  }
  
  Future<com_iflytek_cloud_SpeechEvent> ascom_iflytek_cloud_SpeechEvent() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_cloud_SpeechEvent', {'refId': refId});
    return com_iflytek_cloud_SpeechEvent()..refId = result;
  }
  
  Future<com_iflytek_cloud_resource_Resource> ascom_iflytek_cloud_resource_Resource() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_cloud_resource_Resource', {'refId': refId});
    return com_iflytek_cloud_resource_Resource()..refId = result;
  }
  
  Future<com_iflytek_cloud_WakeuperResult> ascom_iflytek_cloud_WakeuperResult() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_cloud_WakeuperResult', {'refId': refId});
    return com_iflytek_cloud_WakeuperResult()..refId = result;
  }
  
  Future<com_iflytek_cloud_VerifierResult> ascom_iflytek_cloud_VerifierResult() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_cloud_VerifierResult', {'refId': refId});
    return com_iflytek_cloud_VerifierResult()..refId = result;
  }
  
  Future<com_iflytek_cloud_SpeechConstant> ascom_iflytek_cloud_SpeechConstant() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_cloud_SpeechConstant', {'refId': refId});
    return com_iflytek_cloud_SpeechConstant()..refId = result;
  }
  
  Future<com_iflytek_cloud_RecognizerResult> ascom_iflytek_cloud_RecognizerResult() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_cloud_RecognizerResult', {'refId': refId});
    return com_iflytek_cloud_RecognizerResult()..refId = result;
  }
  
  Future<com_iflytek_cloud_TranscripterResult> ascom_iflytek_cloud_TranscripterResult() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_cloud_TranscripterResult', {'refId': refId});
    return com_iflytek_cloud_TranscripterResult()..refId = result;
  }
  
  Future<com_iflytek_cloud_Version> ascom_iflytek_cloud_Version() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_cloud_Version', {'refId': refId});
    return com_iflytek_cloud_Version()..refId = result;
  }
  
  Future<com_iflytek_cloud_UnderstanderResult> ascom_iflytek_cloud_UnderstanderResult() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_cloud_UnderstanderResult', {'refId': refId});
    return com_iflytek_cloud_UnderstanderResult()..refId = result;
  }
  
  Future<com_iflytek_msc_VAD_VadData> ascom_iflytek_msc_VAD_VadData() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_msc_VAD_VadData', {'refId': refId});
    return com_iflytek_msc_VAD_VadData()..refId = result;
  }
  
  Future<com_iflytek_msc_MSCSessionInfo> ascom_iflytek_msc_MSCSessionInfo() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_msc_MSCSessionInfo', {'refId': refId});
    return com_iflytek_msc_MSCSessionInfo()..refId = result;
  }
  
  Future<com_iflytek_msc_MetaVAD> ascom_iflytek_msc_MetaVAD() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_msc_MetaVAD', {'refId': refId});
    return com_iflytek_msc_MetaVAD()..refId = result;
  }
  
  Future<com_iflytek_msc_VAD> ascom_iflytek_msc_VAD() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_msc_VAD', {'refId': refId});
    return com_iflytek_msc_VAD()..refId = result;
  }
  
  Future<com_iflytek_msc_AIMIC> ascom_iflytek_msc_AIMIC() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_msc_AIMIC', {'refId': refId});
    return com_iflytek_msc_AIMIC()..refId = result;
  }
  
  Future<com_iflytek_msc_MSC> ascom_iflytek_msc_MSC() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_msc_MSC', {'refId': refId});
    return com_iflytek_msc_MSC()..refId = result;
  }
  
  Future<com_iflytek_msc_MetaVAD_Instance> ascom_iflytek_msc_MetaVAD_Instance() async {
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('RefClass::ascom_iflytek_msc_MetaVAD_Instance', {'refId': refId});
    return com_iflytek_msc_MetaVAD_Instance()..refId = result;
  }
  
}