// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:xfiat_fluttify/src/ios/ios.export.g.dart';
import 'package:xfiat_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

class IFlyAudioSession extends NSObject  {
  //region constants
  
  //endregion

  //region creators
  static Future<IFlyAudioSession> create__() async {
    final int refId = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('ObjectFactory::createIFlyAudioSession');
    final object = IFlyAudioSession()..refId = refId..tag = 'xfiat_fluttify';
  
    kNativeObjectPool.add(object);
    return object;
  }
  
  //endregion

  //region getters
  
  //endregion

  //region setters
  
  //endregion

  //region methods
  static Future<void> initPlayingAudioSession(bool isMPCenter) async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: IFlyAudioSession::initPlayingAudioSession([\'isMPCenter\':$isMPCenter])');
    }
  
    // invoke native method
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('IFlyAudioSession::initPlayingAudioSession', {"isMPCenter": isMPCenter});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
    
      return result;
    }
  }
  
  static Future<bool> initRecordingAudioSession() async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: IFlyAudioSession::initRecordingAudioSession([])');
    }
  
    // invoke native method
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('IFlyAudioSession::initRecordingAudioSession', );
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
    
      return result;
    }
  }
  
  //endregion
}