// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:xfiat_fluttify/src/ios/ios.export.g.dart';
import 'package:xfiat_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

class IFlyVerifierUtil extends NSObject  {
  //region constants
  
  //endregion

  //region creators
  static Future<IFlyVerifierUtil> create__() async {
    final int refId = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('ObjectFactory::createIFlyVerifierUtil');
    final object = IFlyVerifierUtil()..refId = refId..tag = 'xfiat_fluttify';
  
    kNativeObjectPool.add(object);
    return object;
  }
  
  //endregion

  //region getters
  
  //endregion

  //region setters
  
  //endregion

  //region methods
  static Future<String> generateNumberPassword(int length) async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: IFlyVerifierUtil::generateNumberPassword([\'length\':$length])');
    }
  
    // invoke native method
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('IFlyVerifierUtil::generateNumberPassword', {"length": length});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
    
      return result;
    }
  }
  
  static Future<UIImage> ARGBToGray(UIImage sourceImage) async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: IFlyVerifierUtil::ARGBToGray([])');
    }
  
    // invoke native method
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('IFlyVerifierUtil::ARGBToGray', {"sourceImage": sourceImage.refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
      kNativeObjectPool.add(UIImage()..refId = result..tag = 'xfiat_fluttify');
      return UIImage()..refId = result..tag = 'xfiat_fluttify';
    }
  }
  
  //endregion
}