// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:xfiat_fluttify/src/ios/ios.export.g.dart';
import 'package:xfiat_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

mixin IFlyPcmRecorderDelegate on NSObject {
  

  

  

  @mustCallSuper
  Future<void> onIFlyRecorderVolumeChanged(int power) {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('onIFlyRecorderVolumeChanged::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
}