// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:xfiat_fluttify/src/ios/ios.export.g.dart';
import 'package:xfiat_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

class com_iflytek_speech_VoiceWakeuperAidl extends java_lang_Object  {
  //region constants
  static final String IVW_THRESHOLD = "ivw_threshold";
  static final String IVW_WORD_ID = "ivw_word_id";
  static final String IVW_FILES = "ivw_files";
  static final String PROVIDER_NAME = "com.iflytek.speech.SharedProvider";
  static final String ARG_RES_PROVIDER_AUTHORITY = "content_provider_name";
  static final String PARAMS_SEPARATE = ";";
  static final String IVP_USER_NAME = "ivp_user_name";
  static final String IVP_RES_ID = "ivp_res_id";
  static final String IVW_AND_IVP = "ivw_and_ivp";
  static final String WAKEUP_RESULT_ID = "wakeup_result_id";
  static final String WAKEUP_RESULT_SCORE = "wakeup_result_Score";
  static final String ARG_RES_TYPE = "engine_res_type";
  static final int RES_FROM_ASSETS = 257;
  static final int RES_SPECIFIED = 258;
  static final int RES_FROM_CLIENT = 259;
  //endregion

  //region creators
  
  //endregion

  //region getters
  
  //endregion

  //region setters
  
  //endregion

  //region methods
  Future<bool> destroy() async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.iflytek.speech.VoiceWakeuperAidl@$refId::destroy([])');
    }
  
    // invoke native method
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('com.iflytek.speech.VoiceWakeuperAidl::destroy', {"refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
    
      return result;
    }
  }
  
  Future<bool> isListening() async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.iflytek.speech.VoiceWakeuperAidl@$refId::isListening([])');
    }
  
    // invoke native method
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('com.iflytek.speech.VoiceWakeuperAidl::isListening', {"refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
    
      return result;
    }
  }
  
  Future<int> setParameter(String var1, String var2) async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.iflytek.speech.VoiceWakeuperAidl@$refId::setParameter([\'var1\':$var1, \'var2\':$var2])');
    }
  
    // invoke native method
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('com.iflytek.speech.VoiceWakeuperAidl::setParameter', {"var1": var1, "var2": var2, "refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
    
      return result;
    }
  }
  
  Future<String> getParameter(String var1) async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.iflytek.speech.VoiceWakeuperAidl@$refId::getParameter([\'var1\':$var1])');
    }
  
    // invoke native method
    final result = await MethodChannel('com.fluttify/xfiat_fluttify').invokeMethod('com.iflytek.speech.VoiceWakeuperAidl::getParameter', {"var1": var1, "refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
    
      return result;
    }
  }
  
  //endregion
}